
const SHOW_PANEL_TODO = 'SHOW_PANEL_TODO';

const SELECT_TODO_ID = 'SELECT_TODO_ID'
const SELECT_LIST_ID = 'SELECT_LIST_ID'

const SET_ACTIV_TAB = 'SET_ACTIV_TAB'


export { SHOW_PANEL_TODO, SELECT_TODO_ID, SELECT_LIST_ID, SET_ACTIV_TAB };