
const SHOW_PANEL_TODO = 'SHOW_PANEL_TODO';
const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW';
const SHOW_CONFIRM_WINDOW = 'SHOW_CONFIRM_WINDOW';
const SHOW_DELETE_LIST_WINDOW = 'SHOW_DELETE_LIST_WINDOW';
const SHOW_RENAME_WINDOW = 'SHOW_RENAME_WINDOW';
const SHOW_ADD_LIST_WINDOW = 'SHOW_ADD_LIST_WINDOW';
const SHOW_SETTINGS_WINDOW = 'SHOW_SETTINGS_WINDOW';

const SELECT_TODO_ID = 'SELECT_TODO_ID'
const SELECT_LIST_ID = 'SELECT_LIST_ID'

const SET_ACTIV_TAB = 'SET_ACTIV_TAB'
const SEARCH_STRING= 'SEARCH_STRING'


export { SHOW_PANEL_TODO, 
         SELECT_TODO_ID, 
         SELECT_LIST_ID, 
         SET_ACTIV_TAB,
         SHOW_MODAL_WINDOW,
         SHOW_CONFIRM_WINDOW,
         SHOW_RENAME_WINDOW,
         SHOW_DELETE_LIST_WINDOW,
         SHOW_ADD_LIST_WINDOW,
         SHOW_SETTINGS_WINDOW,
         SEARCH_STRING,
         };