
const SHOW_PANEL_TODO = 'SHOW_PANEL_TODO';
const SHOW_SETTINGS_WINDOW = 'SHOW_SETTINGS_WINDOW';
const SHOW_CONFIRM_DIALOG ='SHOW_CONFIRM_DIALOG';
const SHOW_INPUT_MODAL ='SHOW_INPUT_MODAL';

const SELECT_TODO_ID = 'SELECT_TODO_ID'
const SELECT_LIST_ID = 'SELECT_LIST_ID'

const SET_ACTIV_TAB = 'SET_ACTIV_TAB'
const SEARCH_STRING= 'SEARCH_STRING'


export { 
    SHOW_PANEL_TODO, 
    SELECT_TODO_ID, 
    SELECT_LIST_ID, 
    SET_ACTIV_TAB,
    SHOW_SETTINGS_WINDOW,
    SEARCH_STRING,
    SHOW_CONFIRM_DIALOG,
    SHOW_INPUT_MODAL,
};