const TODO_COMPLETE = 'TODO_COMPLETE';
const TODO_IMPORTANT = 'TODO_IMPORTANT';
const TODO_SELECTED = 'TODO_SELECTED';
const CHANGE_HEADER = 'CHANGE_HEADER'
const CHANGE_DATE = 'CHANGE_DATE';
const DELETE_TODO = 'DELETE_TODO';
const DELETE_LIST = 'DELETE_LIST';
const CHANGE_TODO_TITLE = 'CHANGE_TODO_TITLE';
const CHANGE_TODO_NOTE = 'CHANGE_TODO_NOTE'
const ADD_TODO = 'ADD_TODO';
const ADD_IMPORTANT_TODO = 'ADD_IMPORTANT_TODO';
const ADD_LIST = 'ADD_LIST';
const SHOW_ALL_TODOS = 'SHOW_ALL_TODOS';

export { 
	TODO_COMPLETE,
	TODO_IMPORTANT,
	TODO_SELECTED,
	CHANGE_HEADER,
	CHANGE_DATE,
	DELETE_TODO,
	CHANGE_TODO_TITLE,
	CHANGE_TODO_NOTE,
	ADD_TODO,
	ADD_IMPORTANT_TODO,
	ADD_LIST,
	DELETE_LIST,
	SHOW_ALL_TODOS,
};